name: delete-older-releases
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # runs at every 12AM UTC
    
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    
    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 0
    
    - name: 删除旧的Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
